// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkokinehkckhecwpzupd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrb2tpbmVoa2NraGVjd3B6dXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjA2NTIsImV4cCI6MjA2MTEzNjY1Mn0.fpqzf-OzWLP48UxXSPEX33fIdl-lNj4t0ClL03RG4yA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);